DROP TABLE IF EXISTS PURCHASES_ROW;
DROP TABLE IF EXISTS RECEIPTS_ROW;
DROP TABLE IF EXISTS PURCHASES;
DROP TABLE IF EXISTS RECEIPTS;
DROP TABLE IF EXISTS ITEMS;
DROP TABLE IF EXISTS WAREHOUSES;

CREATE TABLE IF NOT EXISTS ITEMS (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    INDEX(name)
 );

CREATE TABLE IF NOT EXISTS WAREHOUSES (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    INDEX(name)
);

CREATE TABLE IF NOT EXISTS RECEIPTS(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    date DATE,
    warehouse_id INTEGER,
    comment VARCHAR(255),
    CONSTRAINT FK_RECEIPTS_WAREHOUSE FOREIGN KEY (warehouse_id) REFERENCES WAREHOUSES(id)
);

CREATE TABLE IF NOT EXISTS RECEIPTS_ROW(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    receipt_id INTEGER,
    item_id INTEGER,
    quantity DECIMAL(15, 3),
    CONSTRAINT FK_RECEIPTS_ROW_RECEIPTS FOREIGN KEY (receipt_id) REFERENCES RECEIPTS(id),
    CONSTRAINT FK_RECEIPTS_ROW_ITEM FOREIGN KEY (item_id) REFERENCES ITEMS(id)
);

CREATE TABLE IF NOT EXISTS PURCHASES(
   id INTEGER AUTO_INCREMENT PRIMARY KEY,
   date DATE,
   warehouse_id INTEGER,
   comment VARCHAR(255),
   CONSTRAINT FK_PURCHASES_WAREHOUSE FOREIGN KEY (warehouse_id) REFERENCES WAREHOUSES(id)
);

CREATE TABLE IF NOT EXISTS PURCHASES_ROW(
   id INTEGER AUTO_INCREMENT PRIMARY KEY,
   purchase_id INTEGER,
   item_id INTEGER,
   quantity DECIMAL(15, 3),
   CONSTRAINT FK_PURCHASES_ROW_PURCHASES FOREIGN KEY (purchase_id) REFERENCES PURCHASES(id),
   CONSTRAINT FK_PURCHASES_ROW_ITEM FOREIGN KEY (item_id) REFERENCES ITEMS(id)
);
