DROP TABLE IF EXISTS RECEIPTS_ROW;
DROP TABLE IF EXISTS RECEIPTS;
DROP TABLE IF EXISTS ITEMS;
DROP TABLE IF EXISTS WAREHOUSES;

CREATE TABLE IF NOT EXISTS ITEMS (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    INDEX(name)
 );

CREATE TABLE IF NOT EXISTS WAREHOUSES (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    INDEX(name)
);

CREATE TABLE IF NOT EXISTS RECEIPTS(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    date DATE,
    warehouse_id INTEGER,
    comment VARCHAR(255),
    CONSTRAINT FK_WAREHOUSE FOREIGN KEY (warehouse_id) REFERENCES WAREHOUSES(id)
);

CREATE TABLE IF NOT EXISTS RECEIPTS_ROW(
    receipt INTEGER,
    receipts_key INTEGER,
    item_id INTEGER,
    quantity DECIMAL(15, 3),
    INDEX(receipt, receipts_key)
);

